name: Terraform azure VM

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VAR_vm_ssh_public_key: ${{ secrets.VM_SSH_PUBLIC_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      id: init
      working-directory: ./project-root
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: ./project-root
      run: terraform validate

    - name: Terraform Plan
      id: plan
      working-directory: ./project-root
      run: terraform plan

    - name: Terraform Apply
      id: apply
      working-directory: ./project-root
      run: terraform apply -auto-approve
    #- name: Terraform Destroy
      #id: destroy
      #working-directory: ./project-root
      #run: terraform destroy -auto-approve

    - name: Get VM Public IP
      id: get_ip
      working-directory: ./project-root
      run: |
        echo "Fetching public IP output..."
        VM_IP=$(terraform output -raw vm_public_ip 2>/dev/null || echo "")
        echo "VM IP: $VM_IP"
        if [[ -z "$VM_IP" ]]; then
        echo "Terraform output 'vm_public_ip' is empty or not found."
        exit 1
        fi
        echo "VM_IP=$VM_IP" >> $GITHUB_ENV
        
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/new_rsa
        chmod 600 ~/.ssh/new_rsa
